config/routes.rb
Rails.application.routes.draw do
  root to: 'tw_clones#top'
  resources :tw_clones do
    collection do
      post  :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tw_clone.rb
class TwClone < ApplicationRecord
  validates :content, presence: true, length: {maximum: 140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tw_clones_controller.rb
class TwClonesController < ApplicationController
  def top
  end
  
  def index
    @twcs = TwClone.all.order(updated_at: :desc)
  end
  
  def new
    @twc = TwClone.new
    p @twc
  end
  
  def confirm
    @twc = TwClone.new(tw_params)
    if @twc.invalid?
      render :new
    end
  end
  
  def create
    @twc = TwClone.new(tw_params)
    p @twc
    if confirm_params == '戻る'
      render :new
    elsif @twc.save
      flash[:notice] = '投稿しました！'
       redirect_to tw_clones_path
    else
      render :new
    end
  end
  
  def edit
    @twc = TwClone.find(params[:id])
  end
  
  def update
    @twc = TwClone.find(params[:id])
    if @twc.update(content: tw_params[:content])
      flash[:notice] = '編集しました！'
      redirect_to tw_clones_path
    else
      render :edit
    end
  end
  
  def destroy
    @twc = TwClone.find(params[:id])
    @twc.destroy
    flash[:notice] = '削除しました！'
    redirect_to tw_clones_path
  end
  
  private
  
  def tw_params
    params.require(:tw_clone).permit(:content)
  end
  
  def confirm_params
    params.require(:commit)
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tw_clones_helper.rb
module TwClonesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwClone</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
  </head>
    <body>
    <header>
      <%= link_to root_path do %><h1>TWCLONE</h1><% end %>
    </header>
    <div id="notice">
      <% if @twc && @twc.errors %>
        <% @twc.errors.full_messages.each do |message| %>
          <p><%= message %></p>
        <% end %>
      <% end %>
      <p><%= flash.now[:notice] %></p>
    </div>
    <nav>
      <ul>
        <li><%= link_to 'トップ', root_path %> </li>
        <li><%= link_to '投稿一覧', tw_clones_path %> </li>
        <li><%= link_to '新規投稿', new_tw_clone_path %> </li>
        <li><s>ログイン</s> </li>
      </ul>
    </nav>

    <%= yield %>

    <footer>5月期生　shimoji kenta</footer>
  </body>
</html>

app/views/tw_clones/confirm.html.erb
<html>
  <head>
    <meta charset="UTF-8">
    <title>twitter_clone</title>
  </head>
  <body>
    <article>
      <div class = "main">
        <div id="index">
          <div class = "wrapper">
            <ul class="new">
              <h2>投稿確認</h2>
              <%= form_with(model: @twc, local: true, url: tw_clones_path ) do | form| %>
              <%= form.hidden_field :content %>
              <p id="confirm"><%=@twc.content %></p>
              <div><%= form.submit('投稿する') %></div>
              <div><%= form.submit('戻る', commit:'back') %></div
            <% end %>
          </ul>
          </div>
        </div>
      </div>
    </article>
  </body>
</html>

app/views/tw_clones/edit.html.erb
<html>
  <head>
    <meta charset="UTF-8">
    <title>twitter_clone</title>
  </head>
  <body>
    <article>
      <div class = "main">
        <div id="index">
          <div class = "wrapper">
            <ul class="new">
            <p>編集する</p>
              <%= form_with(model: @twc, local: true, url: tw_clone_path(@twc.id) ) do | form| %>
                <div><%= form.text_area :content %></div>
                <%= form.submit('編集する') %>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </article>
  </body>
</html>

app/views/tw_clones/index.html.erb
<html>
  <head>
    <meta charset="UTF-8">
    <title>twitter_clone</title>
  </head>
  <body>
    <article>
      <div class = "main">
        <div id="index">
          <div class= "wrapper"> <!-- 格納用タグ -->
            <h1>投稿一覧</h1>
              <% @twcs.each do |twc| %>
                <ul>
                  <p><%= twc.updated_at.in_time_zone('Tokyo').strftime('%Y/%D %H:%M:%S') %></p>
                  <div id="contribution">
                    <li><%= twc.content %></li>
                    <li>
                      <%= link_to edit_tw_clone_path(twc.id) do %>
                        <i class="fas fa-edit"></i>
                      <% end %>
                      <%= link_to tw_clone_path(twc.id),
                        method: :delete, data: {confirm: "削除しますか？"} do %>
                        <i class="fas fa-trash-alt"></i>
                      <% end %>
                    </li>
                  </div>
                </ul>
              <% end %>
          </div>
        </div>
      </div>
    </article>
  </body>
</html>

app/views/tw_clones/new.html.erb
<html>
  <head>
    <meta charset="UTF-8">
    <title>twitter_clone</title>
  </head>
  <body>
    <article>
      <div class = "main">
        <div id="index">
          <div class = "wrapper">
            <ul class="new">
              <p>新規投稿</p>
              <%= form_with(model: @twc, local: true, url: confirm_tw_clones_path ) do | form| %>
              <div><%= form.text_area :content %></div>
              <%= form.submit('投稿する') %>
            <% end %>
          </ul>
          </div>
        </div>
      </div>
    </article>
  </body>
</html>

app/views/tw_clones/top.html.erb
<html>
  <head>
    <meta charset="UTF-8">
    <title>twitter_clone</title>
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
  </head>
  <body>
    <article>
      <div class = "main">
        <div id="opa_mask">
          <h1>Tw Clone</h1>
        </div>
      </div>
    </article>
  </body>
</html>